// <auto-generated />
using System;
using BeatlesTrackDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeatlesTracksDB.Migrations
{
    [DbContext(typeof(BeatlesTrackDBContext))]
    [Migration("20211023161344_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeatlesTracksDB.Models.ItunesTrackslist", b =>
                {
                    b.Property<int>("trackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("artistId")
                        .HasColumnType("int");

                    b.Property<string>("collectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("collectionPrice")
                        .HasColumnType("float");

                    b.Property<string>("kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primaryGenreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("trackCount")
                        .HasColumnType("int");

                    b.Property<string>("trackName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trackNumber")
                        .HasColumnType("int");

                    b.Property<double>("trackPrice")
                        .HasColumnType("float");

                    b.HasKey("trackId");

                    b.ToTable("ItunesTrackslist");
                });
#pragma warning restore 612, 618
        }
    }
}
