apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatlestracksdb
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beatlestracksdb
  template:
    metadata:
      labels:
        app: beatlestracksdb
    spec:
      containers:
      - name: beatlestracksdb
        image: adocr01.azurecr.io/beatlestracksdb:#BuildTag1#
        env:
          - name: ConnectionStrings__BeatlesTrackDBContext
            valueFrom:
              secretKeyRef:
                key: database_connectionstring
                name: beatlestracksdbsecret
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: beatlestracksdb
  namespace: dev
spec:
  selector:
    app: beatlestracksdb
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
