trigger: none

resources:
  pipelines:
  - pipeline: DEV_BuildAndPush
    source: DEV_BuildAndPush
    trigger: true

stages:
- stage: Deploy
  displayName: Deploy to dev

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS (dev env)
    environment: $(k8sEnv)
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'specific'
              artifact: 'manifests'
              path: '$(Pipeline.Workspace)/manifests'
              project: 'BeatlesTracksDBVSS'
              pipeline: $(SourcePipelineArtifact)
              runVersion: 'latest'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                ls -lR $(Pipeline.Workspace)/manifests
                tree $(Pipeline.Workspace)/manifests
                cat $(Pipeline.Workspace)/manifests/dbsecret.yml
          - task: replacetokens@3
            displayName: Replace Tokens
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/manifests/'
              targetFiles: 'dbsecret.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#'
              tokenSuffix: '#'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true   
            env:
              DBConnectionString: $(DBConnectionString)       
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                ls -lR $(Pipeline.Workspace)/manifests
                tree $(Pipeline.Workspace)/manifests
                cat $(Pipeline.Workspace)/manifests/dbsecret.yml
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              namespace: 'dev'
              manifests: |
                $(Pipeline.Workspace)/manifests/dbsecret.yml
                $(Pipeline.Workspace)/manifests/beatlestracksdb.yml              
              imagePullSecrets: '$(acrsecret)'
