stages:
- stage: Deploy
  displayName: Deploy to dev
  variables:
    DBConnectionString: $(DBConnectionString)
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'k8s.dev'
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'specific'
              artifact: 'manifests'
              path: '$(Pipeline.Workspace)/manifests'
              project: 'BeatlesTracksDBVSS'
              pipeline: 11
              runVersion: 'latest'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                ls -lR $(Pipeline.Workspace)/manifests
                tree $(Pipeline.Workspace)/manifests
