trigger:
  batch: true
  branches:
    include:
      - IaC

pool:
  vmImage: ubuntu-latest

jobs:
- job:
  steps:

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
       az deployment group create --resource-group $(ResourceGroupName) --template-file IaC/AKSDeployment.bicep