resources:
  pipelines:
  - pipeline: BuildAndPush
    source: Prod_BuildAndPush
    trigger:
      branches:
        include:
        - main

variables: 
  K8sEnv: prod
  
trigger: none
stages:
- stage: Deploy
  displayName: Deploy to prod

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: k8s.prod
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'specific'
              artifact: 'manifests'
              path: '$(Pipeline.Workspace)/manifests'
              project: 'BeatlesTracksDBVSS'
              pipeline: 'Prod_BuildAndPush'
              runVersion: 'latest'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                ls -lR $(Pipeline.Workspace)/manifests
                tree $(Pipeline.Workspace)/manifests
                cat $(Pipeline.Workspace)/manifests/dbsecret.yml
          - task: replacetokens@3
            displayName: Replace Tokens (dbsecret)
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/manifests/'
              targetFiles: 'dbsecret.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '##'
              tokenSuffix: '##'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true
              verbosity: detailed
            env:
              DBConnectionString: $(DBConnectionString)
          - task: replacetokens@3
            displayName: Replace Tokens (deployment & service)
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/manifests/'
              targetFiles: 'beatlestracksdb.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '##'
              tokenSuffix: '##'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: true
              verbosity: detailed
            env:
              DBConnectionString: $(DBConnectionString)
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                ls -lR $(Pipeline.Workspace)/manifests
                tree $(Pipeline.Workspace)/manifests
                cat $(Pipeline.Workspace)/manifests/dbsecret.yml
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              namespace: 'prod'
              manifests: |
                $(Pipeline.Workspace)/manifests/dbsecret.yml
                $(Pipeline.Workspace)/manifests/beatlestracksdb.yml              
              imagePullSecrets: '$(acrsecret)'
